[package]
edition = "2021"
name = "scrape_url"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2md = "0.2"
reqwest = {version = "0.11", features = ["blocking"]}
structopt = "0.3"
