[package]
name = "todo-cli"
version = "0.1.0"
authors = ["custer-go <custertian@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
